baseurl = "https://darshancrout.ai/"
title = "Darshan Crout"
theme ="hugo-theme-basic"
languageCode = "en-us"
googleAnalytics = "UA-133534404-1"
enableEmoji = true
copyright = "Â© 2019 Darshan Crout (<a href='https://twitter.com/durshmallow'>@durshmallow</a>). All rights reserved."
description = ""

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = "ğŸŠğŸš´â€â™‚ï¸ğŸƒâ€â™‚ï¸ğŸ‘¨â€ğŸ’»"
  # change this!
  twitter = "durshmallow"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "posts"
  url = "post/"

# [[params.menu]]
#   name = "post series"
#   url = "series/"

[[params.menu]]
  name = "now"
  url = "now/"

[[params.menu]]
  name = "setup"
  url = "setup/"

[[params.menu]]
  name = "about"
  url = "about/"

[[params.menu]]
  name = "rss"
  url = "index.xml"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
